const fs=require('fs'); const path=require('path'); const Database=require('better-sqlite3');
const dir=path.join(__dirname,'data'); fs.mkdirSync(dir,{recursive:true}); const db=new Database(path.join(dir,'nestlink.db')); db.pragma('foreign_keys=ON');
const schema=`
CREATE TABLE IF NOT EXISTS Residences(residence_id INTEGER PRIMARY KEY AUTOINCREMENT,res_name TEXT NOT NULL UNIQUE,is_active INTEGER NOT NULL DEFAULT 1 CHECK(is_active IN(0,1)));
CREATE TABLE IF NOT EXISTS Users(user_id INTEGER PRIMARY KEY AUTOINCREMENT,email TEXT NOT NULL UNIQUE,password_hash TEXT NOT NULL,full_name TEXT NOT NULL,role TEXT NOT NULL CHECK(role IN('student','residence_staff')),residence_id INTEGER,is_active INTEGER NOT NULL DEFAULT 1,last_login TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(residence_id) REFERENCES Residences(residence_id));
CREATE TABLE IF NOT EXISTS Rooms(room_id INTEGER PRIMARY KEY AUTOINCREMENT,residence_id INTEGER NOT NULL,room_number TEXT NOT NULL,floor_no INTEGER NOT NULL DEFAULT 0,capacity INTEGER NOT NULL DEFAULT 1,status TEXT NOT NULL DEFAULT 'available' CHECK(status IN('available','occupied','maintenance')),UNIQUE(residence_id,room_number),FOREIGN KEY(residence_id) REFERENCES Residences(residence_id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS RoomAllocations(allocation_id INTEGER PRIMARY KEY AUTOINCREMENT,room_id INTEGER NOT NULL,student_user_id INTEGER NOT NULL,academic_year INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'active' CHECK(status IN('active','ended')),allocated_on TEXT NOT NULL DEFAULT CURRENT_DATE,ended_on TEXT,allocated_by INTEGER,FOREIGN KEY(room_id) REFERENCES Rooms(room_id),FOREIGN KEY(student_user_id) REFERENCES Users(user_id),FOREIGN KEY(allocated_by) REFERENCES Users(user_id));
CREATE UNIQUE INDEX IF NOT EXISTS uq_active_student_allocation ON RoomAllocations(student_user_id) WHERE status='active';
CREATE TABLE IF NOT EXISTS MaintenanceCategories(category_id INTEGER PRIMARY KEY AUTOINCREMENT,category_name TEXT NOT NULL UNIQUE,target_hours INTEGER NOT NULL DEFAULT 72);
CREATE TABLE IF NOT EXISTS ItemCatalog(item_id INTEGER PRIMARY KEY AUTOINCREMENT,item_name TEXT NOT NULL UNIQUE,item_group TEXT NOT NULL,description TEXT,default_quantity INTEGER NOT NULL DEFAULT 1,replacement_cost REAL NOT NULL DEFAULT 0);
CREATE TABLE IF NOT EXISTS RoomInventory(room_item_id INTEGER PRIMARY KEY AUTOINCREMENT,room_id INTEGER NOT NULL,item_id INTEGER NOT NULL,quantity_expected INTEGER NOT NULL DEFAULT 1,current_condition TEXT NOT NULL DEFAULT 'good' CHECK(current_condition IN('good','fair','damaged','missing')),UNIQUE(room_id,item_id),FOREIGN KEY(room_id) REFERENCES Rooms(room_id) ON DELETE CASCADE,FOREIGN KEY(item_id) REFERENCES ItemCatalog(item_id));
CREATE TABLE IF NOT EXISTS InventoryChecks(check_id INTEGER PRIMARY KEY AUTOINCREMENT,allocation_id INTEGER NOT NULL,room_id INTEGER NOT NULL,student_user_id INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN('draft','submitted','verified','disputed')),signature_name TEXT,signed_at TEXT,verified_by INTEGER,verified_at TEXT,verifier_note TEXT,opened_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(allocation_id) REFERENCES RoomAllocations(allocation_id),FOREIGN KEY(room_id) REFERENCES Rooms(room_id),FOREIGN KEY(student_user_id) REFERENCES Users(user_id),FOREIGN KEY(verified_by) REFERENCES Users(user_id));
CREATE TABLE IF NOT EXISTS MaintenanceReports(report_id INTEGER PRIMARY KEY AUTOINCREMENT,reference_code TEXT NOT NULL UNIQUE,room_id INTEGER NOT NULL,reported_by INTEGER NOT NULL,category_id INTEGER NOT NULL,item_id INTEGER,title TEXT NOT NULL,description TEXT NOT NULL,priority TEXT NOT NULL DEFAULT 'normal' CHECK(priority IN('low','normal','high','urgent')),source TEXT NOT NULL DEFAULT 'student' CHECK(source IN('student','inventory','residence')),status TEXT NOT NULL DEFAULT 'submitted' CHECK(status IN('submitted','acknowledged','in_progress','completed','closed')),resolution_note TEXT,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(room_id) REFERENCES Rooms(room_id),FOREIGN KEY(reported_by) REFERENCES Users(user_id),FOREIGN KEY(category_id) REFERENCES MaintenanceCategories(category_id),FOREIGN KEY(item_id) REFERENCES ItemCatalog(item_id));
CREATE TABLE IF NOT EXISTS InventoryCheckItems(check_item_id INTEGER PRIMARY KEY AUTOINCREMENT,check_id INTEGER NOT NULL,room_item_id INTEGER NOT NULL,item_id INTEGER NOT NULL,quantity_found INTEGER NOT NULL DEFAULT 1,condition_rating TEXT CHECK(condition_rating IN('good','fair','damaged','missing')),student_comment TEXT,raise_report INTEGER NOT NULL DEFAULT 0,report_id INTEGER,UNIQUE(check_id,room_item_id),FOREIGN KEY(check_id) REFERENCES InventoryChecks(check_id) ON DELETE CASCADE,FOREIGN KEY(room_item_id) REFERENCES RoomInventory(room_item_id),FOREIGN KEY(item_id) REFERENCES ItemCatalog(item_id),FOREIGN KEY(report_id) REFERENCES MaintenanceReports(report_id));
CREATE TABLE IF NOT EXISTS Notifications(notification_id INTEGER PRIMARY KEY AUTOINCREMENT,user_id INTEGER NOT NULL,title TEXT NOT NULL,message TEXT NOT NULL,type TEXT NOT NULL DEFAULT 'general',link_id INTEGER,is_read INTEGER NOT NULL DEFAULT 0,created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id) REFERENCES Users(user_id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_rooms_res ON Rooms(residence_id); CREATE INDEX IF NOT EXISTS idx_reports_room ON MaintenanceReports(room_id); CREATE INDEX IF NOT EXISTS idx_notif_user ON Notifications(user_id,is_read);`;
db.exec(schema);
const seed=db.transaction(()=>{
 const insRes=db.prepare('INSERT OR IGNORE INTO Residences(res_name) VALUES(?)'); ['STUDENT VILLAGE 1','STUDENT VILLAGE 2','STUDENT VILLAGE 3','STUDENT VILLAGE 4'].forEach(x=>insRes.run(x));
 const insCat=db.prepare('INSERT OR IGNORE INTO MaintenanceCategories(category_name,target_hours) VALUES(?,?)'); [['Electrical',24],['Plumbing',24],['Furniture',72],['Doors & Windows',48],['General',72]].forEach(x=>insCat.run(...x));
 const insItem=db.prepare('INSERT OR IGNORE INTO ItemCatalog(item_name,item_group,description,default_quantity,replacement_cost) VALUES(?,?,?,?,?)'); [['Study Desk','furniture','Student study desk',1,1200],['Chair','furniture','Study chair',1,650],['Bed','furniture','Residence bed frame',1,1800],['Mattress','soft_furnishing','Single mattress',1,1400],['Wardrobe','furniture','Built-in or freestanding wardrobe',1,2200],['Light','electrical','Room light fitting',1,300],['Power Outlet','electrical','Wall power outlet',2,250]].forEach(x=>insItem.run(...x));
 const residences=db.prepare('SELECT residence_id FROM Residences').all(); const items=db.prepare('SELECT item_id,default_quantity FROM ItemCatalog').all();
 const room=db.prepare('INSERT OR IGNORE INTO Rooms(residence_id,room_number,floor_no,capacity) VALUES(?,?,?,?)'); const roomId=db.prepare('SELECT room_id FROM Rooms WHERE residence_id=? AND room_number=?'); const inv=db.prepare('INSERT OR IGNORE INTO RoomInventory(room_id,item_id,quantity_expected) VALUES(?,?,?)');
 for(const r of residences){for(let n=101;n<=106;n++){room.run(r.residence_id,String(n),1,1); const rid=roomId.get(r.residence_id,String(n)).room_id; for(const i of items)inv.run(rid,i.item_id,i.default_quantity);}}
}); seed(); db.close(); console.log('UFH NestLink SQLite database initialized. No user accounts were seeded.');
